const USER_PERMISSION = {
    READ_MESSAGE: "READ_MESSAGE",
    WRITE_MESSAGE: "WRITE_MESSAGE",
    DELETE_MESSAGE: "DELETE_MESSAGE",
    
    CREATE_CHANNELS: "CREATE_CHANNELS",
    DELETE_CHANNELS: "DELETE_CHANNELS",
    UPDATE_CHANNELS: "UPDATE_CHANNELS",

    CREATE_ROLES: "CREATE_ROLES",
    DELETE_ROLES: "DELETE_ROLES",
    UPDATE_ROLES: "UPDATE_ROLES",

    ADD_USERS: "ADD_USERS",
    REMOVE_USERS: "REMOVE_USERS",
    UPDATE_USERS: "UPDATE_USERS",

    SCHEDULE_HUDDLE: "SCHEDULE_HUDDLE",
    JOIN_HUDDLE: "JOIN_HUDDLE",
    CANCELL_HUDDLE: "CANCELL_HUDDLE",
};

module.exports = USER_PERMISSION;